apiVersion: v2
name: strimzi-operator
description: Wrapper chart for strimzi-kafka-operator
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: strimzi-kafka-operator
    version: 0.49.1
    repository: https://strimzi.io/charts/
