apiVersion: v2
name: minio
description: Wrapper chart for minio
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
