apiVersion: v2
name: monitoring-stack
description: Wrapper chart for kube-prometheus-stack with custom ingress and retention
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 61.3.1
    repository: https://prometheus-community.github.io/helm-charts
