apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: main-db
  namespace: database
spec:
  instances: 1
  
  # Allow traffic from all pods in the cluster (e.g. Ingress/Cloudflared)
  pg_hba:
    - host all all all scramble-sha-256

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"

  storage:
    size: 5Gi
    storageClass: local-path
