apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # This first
spec:
  project: default
  source:
    repoURL: git@github.com:baranacikgoz/homelab-infra.git
    targetRevision: main
    path: clusters/mac-mini/apps/cnpg-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
