apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.12.1
    helm:
      values: |
        args:
          - --kubelet-preferred-address-types=InternalDNS,InternalIP,ExternalIP,Hostname
          - --kubelet-use-node-status-port
          - --metric-resolution=15s
          - --kubelet-insecure-tls

        # --- ORBSTACK İÇİN SİHİRLİ DOKUNUŞ BURASI ---
        extraVolumeMounts:
          - name: kubelet-config
            mountPath: /etc/kubernetes/kubelet.conf
            readOnly: true
        extraVolumes:
          - name: kubelet-config
            hostPath:
              path: /var/lib/kubelet/kubelet.conf
        # ----------------------------------------

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
