apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        mode: standalone
        replicas: 1

        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi

        persistence:
          size: 10Gi

        rootUser: "admin"
        rootPassword: "changeme123"

        # --- KRİTİK AYAR 1: ORTAM DEĞİŞKENLERİ ---
        # MinIO'ya dış adreslerini öğretiyoruz ki port eklemesin
        environment:
          MINIO_SERVER_URL: "https://minio.baranacikgoz.com"
          MINIO_BROWSER_REDIRECT_URL: "https://console.minio.baranacikgoz.com"

        # --- KRİTİK AYAR 2: INGRESS AYRIMI ---

        # 1. API İçin Ingress (S3 trafiği - Port 9000)
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-body-size: "0" # Limitsiz upload
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
          hosts:
            - minio.baranacikgoz.com

        # 2. Console İçin Ingress (Web Arayüzü - Port 9001)
        consoleIngress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            
            # --- KRİTİK EKLENTİLER (KOPMALARI ÖNLER) ---
            nginx.ingress.kubernetes.io/proxy-buffering: "off"
            nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            # -------------------------------------------
            
          hosts:
            - console.minio.baranacikgoz.com
          # --- ÇÖZÜM BURASI: SERVİSİ ZORLUYORUZ ---
          # Helm'in tahmin etmesini beklemeden servisi ve portu biz söylüyoruz
          service:
            name: minio-console
            port: 9001
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
