apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        mode: standalone
        replicas: 1

        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi

        persistence:
          size: 10Gi

        rootUser: "admin"
        rootPassword: "changeme123"

        # --- KRİTİK AYAR 1: ORTAM DEĞİŞKENLERİ ---
        # MinIO'ya dış adreslerini öğretiyoruz ki port eklemesin
        environment:
          MINIO_SERVER_URL: "https://minio.baranacikgoz.com"
          MINIO_BROWSER_REDIRECT_URL: "https://console.minio.baranacikgoz.com"

        ingress:
          enabled: false # manuel ingress tanımı yapacağız
        consoleIngress:
          enabled: false # manuel ingress tanımı yapacağız

          hosts:
            - console.minio.baranacikgoz.com
          # --- ÇÖZÜM BURASI: SERVİSİ ZORLUYORUZ ---
          # Helm'in tahmin etmesini beklemeden servisi ve portu biz söylüyoruz
          service:
            name: minio-console
            port: 9001
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
