apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        mode: standalone
        replicas: 1
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
        persistence:
          size: 10Gi
        rootUser: "admin"
        rootPassword: "changeme123"

        environment:
          # BURASI ÇOK ÖNEMLİ: MinIO'ya "Sen HTTP çalış ama dış dünyadaki adresin budur" diyoruz.
          MINIO_SERVER_URL: "https://minio.baranacikgoz.com"
          MINIO_BROWSER_REDIRECT_URL: "https://console.minio.baranacikgoz.com"
          # Ekstra Güvenlik/Uyumluluk
          MINIO_SERVER_PORT: "9000"
          MINIO_BROWSER_PORT: "9001"

        # API INGRESS
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            # Nginx'e dışarının HTTPS olduğunu fısıldıyoruz
            nginx.ingress.kubernetes.io/configuration-snippet: |
              proxy_set_header X-Forwarded-Proto https;
          hosts:
            - minio.baranacikgoz.com

        # CONSOLE INGRESS
        consoleIngress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/proxy-buffering: "off"
            # Nginx'e dışarının HTTPS olduğunu fısıldıyoruz
            nginx.ingress.kubernetes.io/configuration-snippet: |
              proxy_set_header X-Forwarded-Proto https;
          hosts:
            - console.minio.baranacikgoz.com
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
