apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.43.0
    helm:
      values: |
        resources:
          requests:
            memory: 384Mi
            cpu: 250m
          limits:
            memory: 768Mi
            # CPU Limitini 1 Core'a çıkarıyoruz ki açılışta boğulmasın
            cpu: 1000m 

        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 20

        # --- KRİTİK DÜZELTME ---
        # 1. Blocked Thread Check süresini 2sn'den 60sn'ye çıkarıyoruz.
        # 2. Garbage Collector'ı optimize ediyoruz.
        extraEnvs:
          - name: JAVA_TOOL_OPTIONS
            value: "-Xms384m -Xmx384m -XX:+UseG1GC -Dvertx.blockedThreadCheckInterval=60000"
          - name: STRIMZI_RECONCILIATION_INTERVAL_MS
            value: "120000"

        logLevel: INFO
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
