apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-helm
  namespace: argocd
spec:
  project: default
  source:
    # 1. Yeni ve güvenilir repo (Nicholas Wilde)
    repoURL: https://charts.nicholaswilde.io
    chart: vaultwarden
    targetRevision: 1.2.1 # Güncel versiyon
    helm:
      values: |
        image:
          repository: vaultwarden/server
          tag: latest
        
        # Vaultwarden spesifik ayarlar
        domain: "https://passwords.baranacikgoz.com"
        
        env:
          SIGNUPS_ALLOWED: "true"
          WEBSOCKET_ENABLED: "true"
        
        # Depolama ayarları
        persistence:
          enabled: true
          size: 1Gi
        
        # Ingress ayarları
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          hosts:
            - host: passwords.baranacikgoz.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls: [] # SSL Cloudflare'de
  
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true