apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: main-cluster
  namespace: logging
spec:
  version: 8.17.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false # For Mac/Orbstack compatibility
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 1Gi
                  cpu: 1
                limits:
                  memory: 1.5Gi
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx1g"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
