apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: main-rabbit
  namespace: rabbitmq-system
spec:
  replicas: 1
  image: rabbitmq:3.12-management # Image with management panel

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m # Needs CPU during startup
      memory: 512Mi


  persistence:
    storageClassName: local-path
    storage: 5Gi

  service:
    type: ClusterIP # We will access it from outside via Ingress or Port-forward
