apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: main-rabbit
  namespace: rabbitmq-system
spec:
  replicas: 1 # Home lab için 1 yeterli
  image: rabbitmq:3.12-management # Yönetim paneli olan imaj

  # --- OPTİMİZASYON ---
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m # Açılışta işlemciye ihtiyaç duyar
      memory: 512Mi # 512MB RAM limiti yeterli
  # --------------------

  persistence:
    storageClassName: local-path # Veya varsayılan neyse
    storage: 5Gi

  service:
    type: ClusterIP # Dışarıya Ingress veya Port-forward ile erişeceğiz
