apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: git@github.com:baranacikgoz/homelab-infra.git
    targetRevision: main
    # Artık Helm chart değil, indirdiğimiz YAML dosyasının olduğu klasör
    path: clusters/mac-mini/apps/rabbitmq-system
  destination:
    server: https://kubernetes.default.svc
    # Operator bu namespace'e kurulacak
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Büyük CRD'ler için gerekli
