apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: main-cluster
  namespace: logging
spec:
  version: 8.17.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false # Mac/Orbstack uyumu için
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              # --- RAM TASARRUFU BURADA ---
              resources:
                requests:
                  memory: 512Mi
                  cpu: 500m
                limits:
                  memory: 1Gi # Asla 1GB'ı geçmesin
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m" # Java Heap sabit 512MB
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
