apiVersion: v2
name: metrics-server
description: Wrapper chart for metrics-server with OrbStack overrides
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: metrics-server
    version: 3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server/
